---
- hosts: webservers
  sudo: yes
  tasks:
    - name: install wget 
      yum: name=wget state=latest
    - name: install unzip
      yum: name=unzip state=latest
    - name: change directory
      command: cd /tmp
    - name: install java
      command: wget -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
    - name: rpm extract
      command: sudo rpm -ivh jdk-8u131-linux-x64.rpm
    - name: download tomcat
      command: wget http://www-eu.apache.org/dist/tomcat/tomcat-8/v8.5.32/bin/apache-tomcat-8.5.32-windows-x64.zip
    - name: unzip tomcat
      command: unzip apache-tomcat-8.5.32-windows-x64.zip
    - name: move tomcat to opt directory
      command: mv apache-tomcat-8.5.32 /opt/tomcat
    - name: update permissions
      command: chmod -R 755 /opt/tomcat
    - name: download sample war file
      command: cd /tmp
    - name: sample war file downloading
      command: wget wget https://osdn.net/frs/redir.php?m=aarnet&f=pal%2F17479%2Fhelloworld.war  
    - name: copy war file to web apps
      command: cp /tmp/helloworld.war /opt/tomcat/webapps
    - name: start tomcat
      command: /opt/tomcat/bin/startup.sh
