---
- hosts: webservers
  sudo: yes
  tasks:
    - name: install java
      yum: name=java update_cache=yes state=latest
    - name: install tomcat
      yum: name=tomcat state=latest
    - name: install wget 
      yum:  name=wget state=latest
    - name: change directory
      command: cd /usr/share/tomcat/webapps
    - name: copy war file to webapps
      command: wget https://osdn.net/frs/redir.php?m=aarnet&f=pal%2F17479%2Fhelloworld.war  
    - name: start tomcat
      service: name=tomcat state=started 
